"""Repository contract. InMemoryRepository and PostgresRepository both implement this,
so routes can depend on the shape without caring which backend is behind it."""

from typing import Protocol
from uuid import UUID

from dispatch_engine.domain import Job, Technician


class Repository(Protocol):
    async def add_technician(self, technician: Technician) -> Technician: ...
    async def get_technician(self, technician_id: UUID) -> Technician | None: ...
    async def list_technicians(self) -> list[Technician]: ...
    async def update_technician(self, technician: Technician) -> None: ...

    async def add_job(self, job: Job) -> Job: ...
    async def get_job(self, job_id: UUID) -> Job | None: ...
    async def list_jobs(self) -> list[Job]: ...
    async def update_job(self, job: Job) -> None: ...
